import '../models/enums/platform_setting_value_type.dart';
import '../models/platform_setting_definition.dart';
import 'platform_setting_keys.dart';

/// Dart source of truth for platform defaults.
///
/// Bootstrap writes [defaultPlatformSettingsFirestoreEntries] to
/// `hkzPlatformSettings/config` when the document is missing; runtime values
/// are read from Firestore and merged with any new keys from this list.
const int kPlatformSettingsSchemaVersion = 1;

List<PlatformSettingDefinition> get defaultPlatformSettingDefinitions => _defs;

final List<PlatformSettingDefinition> _defs = <PlatformSettingDefinition>[
  // —— Team ——
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.minStudentsPerTeam,
    displayName: 'Minimum students per team',
    type: PlatformSettingValueType.integer,
    defaultValue: 2,
    sectionKey: 'team',
    sectionTitle: 'Team rules',
    groupKey: 'formation',
    groupTitle: 'Formation rules',
    description: 'Lower bound for team size when forming teams.',
    min: 1,
    max: 20,
    step: 1,
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.maxStudentsPerTeam,
    displayName: 'Maximum students per team',
    type: PlatformSettingValueType.integer,
    defaultValue: 5,
    sectionKey: 'team',
    sectionTitle: 'Team rules',
    groupKey: 'formation',
    groupTitle: 'Formation rules',
    description: 'Upper bound for team size.',
    min: 1,
    max: 30,
    step: 1,
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.maxTeamsPerFaculty,
    displayName: 'Maximum teams per faculty',
    type: PlatformSettingValueType.integer,
    defaultValue: 8,
    sectionKey: 'team',
    sectionTitle: 'Team rules',
    groupKey: 'formation',
    groupTitle: 'Formation rules',
    description: 'Cap on how many teams a faculty advisor can oversee.',
    min: 1,
    max: 50,
    step: 1,
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.allowPendingSubmissionTeamEdit,
    displayName: 'Allow team edits while submission is pending',
    type: PlatformSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'team',
    sectionTitle: 'Team rules',
    groupKey: 'edit',
    groupTitle: 'Edit rules',
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.freezeTeamAfterSubmitted,
    displayName: 'Freeze team after idea submitted',
    type: PlatformSettingValueType.boolean,
    defaultValue: false,
    sectionKey: 'team',
    sectionTitle: 'Team rules',
    groupKey: 'edit',
    groupTitle: 'Edit rules',
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.allowStudentSwitchAfterRejection,
    displayName: 'Allow student to switch team after rejection',
    type: PlatformSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'team',
    sectionTitle: 'Team rules',
    groupKey: 'edit',
    groupTitle: 'Edit rules',
  ),

  // —— Idea ——
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.maxIdeasPerProblem,
    displayName: 'Max ideas per problem',
    type: PlatformSettingValueType.integer,
    defaultValue: 3,
    sectionKey: 'idea',
    sectionTitle: 'Idea rules',
    groupKey: 'submission',
    groupTitle: 'Submission rules',
    min: 1,
    max: 20,
    step: 1,
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.allowIdeaResubmissionAfterRejection,
    displayName: 'Allow resubmission after rejection',
    type: PlatformSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'idea',
    sectionTitle: 'Idea rules',
    groupKey: 'submission',
    groupTitle: 'Submission rules',
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.requirePaymentBeforeSubmission,
    displayName: 'Require payment before submission',
    type: PlatformSettingValueType.boolean,
    defaultValue: false,
    sectionKey: 'idea',
    sectionTitle: 'Idea rules',
    groupKey: 'submission',
    groupTitle: 'Submission rules',
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.minJudgesPerIdea,
    displayName: 'Minimum judges per idea',
    type: PlatformSettingValueType.integer,
    defaultValue: 2,
    sectionKey: 'idea',
    sectionTitle: 'Idea rules',
    groupKey: 'evaluation',
    groupTitle: 'Evaluation rules',
    min: 1,
    max: 10,
    step: 1,
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.maxJudgesPerIdea,
    displayName: 'Maximum judges per idea',
    type: PlatformSettingValueType.integer,
    defaultValue: 5,
    sectionKey: 'idea',
    sectionTitle: 'Idea rules',
    groupKey: 'evaluation',
    groupTitle: 'Evaluation rules',
    min: 1,
    max: 15,
    step: 1,
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.showJudgeCommentsToStudents,
    displayName: 'Show judge comments to students',
    type: PlatformSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'idea',
    sectionTitle: 'Idea rules',
    groupKey: 'evaluation',
    groupTitle: 'Evaluation rules',
  ),

  // —— Problem ——
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.requireProblemCategoryTheme,
    displayName: 'Require category / theme on problems',
    type: PlatformSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'problem',
    sectionTitle: 'Problem rules',
    groupKey: 'general',
    groupTitle: 'Problem setup',
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.maxProblemAttachments,
    displayName: 'Max attachments per problem',
    type: PlatformSettingValueType.integer,
    defaultValue: 5,
    sectionKey: 'problem',
    sectionTitle: 'Problem rules',
    groupKey: 'general',
    groupTitle: 'Problem setup',
    min: 0,
    max: 20,
    step: 1,
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.allowCrossDepartmentSubmissions,
    displayName: 'Allow cross-department submissions',
    type: PlatformSettingValueType.boolean,
    defaultValue: false,
    sectionKey: 'problem',
    sectionTitle: 'Problem rules',
    groupKey: 'general',
    groupTitle: 'Problem setup',
  ),

  // —— Payment ——
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.coordinatorApprovalRequired,
    displayName: 'Coordinator approval required',
    type: PlatformSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'payment',
    sectionTitle: 'Payment rules',
    groupKey: 'general',
    groupTitle: 'Verification',
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.requirePaymentScreenshot,
    displayName: 'Require payment screenshot',
    type: PlatformSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'payment',
    sectionTitle: 'Payment rules',
    groupKey: 'general',
    groupTitle: 'Verification',
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.requirePaymentAmount,
    displayName: 'Require payment amount',
    type: PlatformSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'payment',
    sectionTitle: 'Payment rules',
    groupKey: 'general',
    groupTitle: 'Verification',
  ),

  // —— User / auth ——
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.accessCodeLength,
    displayName: 'Access code length (digits)',
    type: PlatformSettingValueType.integer,
    defaultValue: 6,
    sectionKey: 'userAuth',
    sectionTitle: 'User & access',
    groupKey: 'access',
    groupTitle: 'Access codes',
    min: 4,
    max: 12,
    step: 1,
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.requireAccessCode,
    displayName: 'Require access code to register',
    type: PlatformSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'userAuth',
    sectionTitle: 'User & access',
    groupKey: 'access',
    groupTitle: 'Access codes',
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.allowDuplicateMobile,
    displayName: 'Allow duplicate mobile numbers',
    type: PlatformSettingValueType.boolean,
    defaultValue: false,
    sectionKey: 'userAuth',
    sectionTitle: 'User & access',
    groupKey: 'identity',
    groupTitle: 'Identity',
  ),

  // —— Leaderboard ——
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.enableLeaderboard,
    displayName: 'Enable leaderboard',
    type: PlatformSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'leaderboard',
    sectionTitle: 'Leaderboard rules',
    groupKey: 'general',
    groupTitle: 'Visibility & scoring',
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.judgeScoreWeight,
    displayName: 'Judge score weight',
    type: PlatformSettingValueType.double,
    defaultValue: 0.6,
    sectionKey: 'leaderboard',
    sectionTitle: 'Leaderboard rules',
    groupKey: 'general',
    groupTitle: 'Visibility & scoring',
    description: 'Blend weight for judge scores (0–1). Innovation weight should complement this.',
    min: 0,
    max: 1,
    step: 0.05,
  ),
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.innovationScoreWeight,
    displayName: 'Innovation score weight',
    type: PlatformSettingValueType.double,
    defaultValue: 0.4,
    sectionKey: 'leaderboard',
    sectionTitle: 'Leaderboard rules',
    groupKey: 'general',
    groupTitle: 'Visibility & scoring',
    description: 'Blend weight for innovation signals (0–1).',
    min: 0,
    max: 1,
    step: 0.05,
  ),

  // —— Upload ——
  const PlatformSettingDefinition(
    key: PlatformSettingKeys.maxUploadSizeMB,
    displayName: 'Max upload size (MB)',
    type: PlatformSettingValueType.integer,
    defaultValue: 25,
    sectionKey: 'upload',
    sectionTitle: 'Upload rules',
    groupKey: 'general',
    groupTitle: 'Limits & formats',
    min: 1,
    max: 500,
    step: 1,
  ),
  PlatformSettingDefinition(
    key: PlatformSettingKeys.allowedImageFormats,
    displayName: 'Allowed image formats',
    type: PlatformSettingValueType.stringList,
    defaultValue: <String>['jpg', 'jpeg', 'png', 'webp'],
    sectionKey: 'upload',
    sectionTitle: 'Upload rules',
    groupKey: 'general',
    groupTitle: 'Limits & formats',
    description: 'Extensions without dot, lowercase.',
  ),
  PlatformSettingDefinition(
    key: PlatformSettingKeys.allowedDocumentFormats,
    displayName: 'Allowed document formats',
    type: PlatformSettingValueType.stringList,
    defaultValue: <String>['pdf', 'doc', 'docx'],
    sectionKey: 'upload',
    sectionTitle: 'Upload rules',
    groupKey: 'general',
    groupTitle: 'Limits & formats',
  ),
  PlatformSettingDefinition(
    key: PlatformSettingKeys.allowedVideoFormats,
    displayName: 'Allowed video formats',
    type: PlatformSettingValueType.stringList,
    defaultValue: <String>['mp4', 'webm'],
    sectionKey: 'upload',
    sectionTitle: 'Upload rules',
    groupKey: 'general',
    groupTitle: 'Limits & formats',
  ),
];

/// Firestore `settings` array entries: `{ key, displayName, value }`.
List<Map<String, dynamic>> defaultPlatformSettingsFirestoreEntries() {
  return defaultPlatformSettingDefinitions
      .map(
        (PlatformSettingDefinition d) => <String, dynamic>{
          'key': d.key,
          'displayName': d.displayName,
          'value': d.defaultValue,
        },
      )
      .toList(growable: false);
}
