/// Hackz contextual workspace navigation (Phase 1 foundation).
library;

export '../core/workspace/workspace_container.dart';
export '../core/workspace/workspace_controller.dart';
export '../core/workspace/workspace_header.dart';
export '../core/workspace/workspace_host.dart';
export '../core/workspace/workspace_navigator.dart';
export '../core/workspace/workspace_route.dart';
export '../core/workspace/workspace_theme.dart';
export '../core/workspace/workspace_transition.dart';
export '../core/workspace/workspace_attachment_counts.dart';
export '../core/workspace/workspace_attachments_summary.dart';
export '../core/workspace/workspace_attachments_panel.dart';
export '../features/attachment/workspace/attachment_workspace.dart';
export 'shared/entity_reference_row.dart';
export 'shared/entity_reference_tile.dart';
export '../core/theme/app_semantic_colors.dart';
export '../shared/workspace/context_launch_surface.dart';
export '../shared/workspace/user_list_identity_lead.dart';
export '../shared/workspace/user_workspace_avatar.dart';
export '../widgets/common/context_pill.dart';
export '../widgets/common/context_pill_group.dart';
export '../widgets/common/context_pill_theme.dart';
export '../widgets/common/context_pill_metrics.dart';
export '../features/idea/workspace/idea_workspace.dart';
export '../features/payment/workspace/payment_workspace.dart';
export 'evaluation/evaluation_workspace.dart';
export '../features/problems/workspace/problem_workspace.dart';
export '../features/team/workspace/team_workspace.dart';
export '../features/user/workspace/user_workspace.dart';
