import '../models/enums/org_setting_value_type.dart';
import '../models/org_setting_definition.dart';
import 'org_setting_keys.dart';

/// Dart source of truth for org-setting defaults.
///
/// Bootstrap writes [defaultOrgSettingsFirestoreEntries] to
/// `hkzOrganizations/{orgId}/settings/org_settings` when the document is missing;
/// runtime values are read from Firestore and merged with any new keys from
/// this list.
const int kOrgSettingsSchemaVersion = 1;

List<OrgSettingDefinition> get defaultOrgSettingDefinitions => _defs;

final List<OrgSettingDefinition> _defs = <OrgSettingDefinition>[
  // —— Team ——
  const OrgSettingDefinition(
    key: OrgSettingKeys.minStudentsPerTeam,
    displayName: 'Minimum students per team',
    type: OrgSettingValueType.integer,
    defaultValue: 2,
    sectionKey: 'team',
    sectionTitle: 'Team rules',
    groupKey: 'formation',
    groupTitle: 'Formation rules',
    description: 'Lower bound for team size when forming teams.',
    min: 1,
    max: 20,
    step: 1,
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.maxStudentsPerTeam,
    displayName: 'Maximum students per team',
    type: OrgSettingValueType.integer,
    defaultValue: 5,
    sectionKey: 'team',
    sectionTitle: 'Team rules',
    groupKey: 'formation',
    groupTitle: 'Formation rules',
    description: 'Upper bound for team size.',
    min: 1,
    max: 30,
    step: 1,
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.maxTeamsPerFaculty,
    displayName: 'Maximum teams per faculty',
    type: OrgSettingValueType.integer,
    defaultValue: 8,
    sectionKey: 'team',
    sectionTitle: 'Team rules',
    groupKey: 'formation',
    groupTitle: 'Formation rules',
    description: 'Cap on how many teams a faculty advisor can oversee.',
    min: 1,
    max: 50,
    step: 1,
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.allowPendingSubmissionTeamEdit,
    displayName: 'Allow team edits while submission is pending',
    type: OrgSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'team',
    sectionTitle: 'Team rules',
    groupKey: 'edit',
    groupTitle: 'Edit rules',
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.freezeTeamAfterSubmitted,
    displayName: 'Freeze team after idea submitted',
    type: OrgSettingValueType.boolean,
    defaultValue: false,
    sectionKey: 'team',
    sectionTitle: 'Team rules',
    groupKey: 'edit',
    groupTitle: 'Edit rules',
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.allowStudentSwitchAfterRejection,
    displayName: 'Allow student to switch team after rejection',
    type: OrgSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'team',
    sectionTitle: 'Team rules',
    groupKey: 'edit',
    groupTitle: 'Edit rules',
  ),

  // —— Idea ——
  const OrgSettingDefinition(
    key: OrgSettingKeys.maxIdeasPerProblem,
    displayName: 'Max ideas per problem',
    type: OrgSettingValueType.integer,
    defaultValue: 3,
    sectionKey: 'idea',
    sectionTitle: 'Idea rules',
    groupKey: 'submission',
    groupTitle: 'Submission rules',
    min: 1,
    max: 20,
    step: 1,
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.allowIdeaResubmissionAfterRejection,
    displayName: 'Allow resubmission after rejection',
    type: OrgSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'idea',
    sectionTitle: 'Idea rules',
    groupKey: 'submission',
    groupTitle: 'Submission rules',
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.requirePaymentBeforeSubmission,
    displayName: 'Require payment before submission',
    type: OrgSettingValueType.boolean,
    defaultValue: false,
    sectionKey: 'idea',
    sectionTitle: 'Idea rules',
    groupKey: 'submission',
    groupTitle: 'Submission rules',
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.minJudgesPerIdea,
    displayName: 'Minimum judges per idea',
    type: OrgSettingValueType.integer,
    defaultValue: 2,
    sectionKey: 'idea',
    sectionTitle: 'Idea rules',
    groupKey: 'evaluation',
    groupTitle: 'Evaluation rules',
    min: 1,
    max: 10,
    step: 1,
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.maxJudgesPerIdea,
    displayName: 'Maximum judges per idea',
    type: OrgSettingValueType.integer,
    defaultValue: 5,
    sectionKey: 'idea',
    sectionTitle: 'Idea rules',
    groupKey: 'evaluation',
    groupTitle: 'Evaluation rules',
    min: 1,
    max: 15,
    step: 1,
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.showJudgeCommentsToStudents,
    displayName: 'Show judge comments to students',
    type: OrgSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'idea',
    sectionTitle: 'Idea rules',
    groupKey: 'evaluation',
    groupTitle: 'Evaluation rules',
  ),

  // —— Problem ——
  const OrgSettingDefinition(
    key: OrgSettingKeys.requireProblemCategoryTheme,
    displayName: 'Require category / theme on problems',
    type: OrgSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'problem',
    sectionTitle: 'Problem rules',
    groupKey: 'general',
    groupTitle: 'Problem setup',
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.maxProblemAttachments,
    displayName: 'Max attachments per problem',
    type: OrgSettingValueType.integer,
    defaultValue: 5,
    sectionKey: 'problem',
    sectionTitle: 'Problem rules',
    groupKey: 'general',
    groupTitle: 'Problem setup',
    min: 0,
    max: 20,
    step: 1,
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.allowCrossDepartmentSubmissions,
    displayName: 'Allow cross-department submissions',
    type: OrgSettingValueType.boolean,
    defaultValue: false,
    sectionKey: 'problem',
    sectionTitle: 'Problem rules',
    groupKey: 'general',
    groupTitle: 'Problem setup',
  ),

  // —— Payment ——
  const OrgSettingDefinition(
    key: OrgSettingKeys.coordinatorApprovalRequired,
    displayName: 'Coordinator approval required',
    type: OrgSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'payment',
    sectionTitle: 'Payment rules',
    groupKey: 'general',
    groupTitle: 'Verification',
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.requirePaymentScreenshot,
    displayName: 'Require payment screenshot',
    type: OrgSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'payment',
    sectionTitle: 'Payment rules',
    groupKey: 'general',
    groupTitle: 'Verification',
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.requirePaymentAmount,
    displayName: 'Require payment amount',
    type: OrgSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'payment',
    sectionTitle: 'Payment rules',
    groupKey: 'general',
    groupTitle: 'Verification',
  ),

  // —— User / auth ——
  const OrgSettingDefinition(
    key: OrgSettingKeys.accessCodeLength,
    displayName: 'Access code length (digits)',
    type: OrgSettingValueType.integer,
    defaultValue: 6,
    sectionKey: 'userAuth',
    sectionTitle: 'User & access',
    groupKey: 'access',
    groupTitle: 'Access codes',
    min: 4,
    max: 12,
    step: 1,
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.requireAccessCode,
    displayName: 'Require access code to register',
    type: OrgSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'userAuth',
    sectionTitle: 'User & access',
    groupKey: 'access',
    groupTitle: 'Access codes',
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.allowDuplicateMobile,
    displayName: 'Allow duplicate mobile numbers',
    type: OrgSettingValueType.boolean,
    defaultValue: false,
    sectionKey: 'userAuth',
    sectionTitle: 'User & access',
    groupKey: 'identity',
    groupTitle: 'Identity',
  ),

  // —— Leaderboard ——
  const OrgSettingDefinition(
    key: OrgSettingKeys.enableLeaderboard,
    displayName: 'Enable leaderboard',
    type: OrgSettingValueType.boolean,
    defaultValue: true,
    sectionKey: 'leaderboard',
    sectionTitle: 'Leaderboard rules',
    groupKey: 'general',
    groupTitle: 'Visibility & scoring',
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.judgeScoreWeight,
    displayName: 'Judge score weight',
    type: OrgSettingValueType.double,
    defaultValue: 0.6,
    sectionKey: 'leaderboard',
    sectionTitle: 'Leaderboard rules',
    groupKey: 'general',
    groupTitle: 'Visibility & scoring',
    description: 'Blend weight for judge scores (0–1). Innovation weight should complement this.',
    min: 0,
    max: 1,
    step: 0.05,
  ),
  const OrgSettingDefinition(
    key: OrgSettingKeys.innovationScoreWeight,
    displayName: 'Innovation score weight',
    type: OrgSettingValueType.double,
    defaultValue: 0.4,
    sectionKey: 'leaderboard',
    sectionTitle: 'Leaderboard rules',
    groupKey: 'general',
    groupTitle: 'Visibility & scoring',
    description: 'Blend weight for innovation signals (0–1).',
    min: 0,
    max: 1,
    step: 0.05,
  ),

  // —— Upload ——
  const OrgSettingDefinition(
    key: OrgSettingKeys.maxUploadSizeMB,
    displayName: 'Max upload size (MB)',
    type: OrgSettingValueType.integer,
    defaultValue: 25,
    sectionKey: 'upload',
    sectionTitle: 'Upload rules',
    groupKey: 'general',
    groupTitle: 'Limits & formats',
    min: 1,
    max: 500,
    step: 1,
  ),
  OrgSettingDefinition(
    key: OrgSettingKeys.allowedImageFormats,
    displayName: 'Allowed image formats',
    type: OrgSettingValueType.stringList,
    defaultValue: <String>['jpg', 'jpeg', 'png', 'webp'],
    sectionKey: 'upload',
    sectionTitle: 'Upload rules',
    groupKey: 'general',
    groupTitle: 'Limits & formats',
    description: 'Extensions without dot, lowercase.',
  ),
  OrgSettingDefinition(
    key: OrgSettingKeys.allowedDocumentFormats,
    displayName: 'Allowed document formats',
    type: OrgSettingValueType.stringList,
    defaultValue: <String>['pdf', 'doc', 'docx'],
    sectionKey: 'upload',
    sectionTitle: 'Upload rules',
    groupKey: 'general',
    groupTitle: 'Limits & formats',
  ),
  OrgSettingDefinition(
    key: OrgSettingKeys.allowedVideoFormats,
    displayName: 'Allowed video formats',
    type: OrgSettingValueType.stringList,
    defaultValue: <String>['mp4', 'webm'],
    sectionKey: 'upload',
    sectionTitle: 'Upload rules',
    groupKey: 'general',
    groupTitle: 'Limits & formats',
  ),
];

/// Firestore `settings` array entries: `{ key, displayName, value }`.
List<Map<String, dynamic>> defaultOrgSettingsFirestoreEntries() {
  return defaultOrgSettingDefinitions
      .map(
        (OrgSettingDefinition d) => <String, dynamic>{
          'key': d.key,
          'displayName': d.displayName,
          'value': d.defaultValue,
        },
      )
      .toList(growable: false);
}
